spring.application.name=Employee_Management_System

spring.datasource.url=jdbc:mysql://localhost:3306/Employee_Management_System
spring.datasource.username=root
spring.datasource.password=8126751034

spring.jpa.hibernate.ddl-auto=update
